apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: circleguard-prod

resources:
  - ../../base/00-namespaces.yaml
  - ../../base/01-secrets.yaml
  - ../../base/02-configmaps.yaml
  - ../../base/10-infrastructure.yaml
  - ../../base/20-services.yaml

commonLabels:
  environment: prod

images:
  - name: circleguard-auth-service
    newTag: prod-latest
  - name: circleguard-identity-service
    newTag: prod-latest
  - name: circleguard-form-service
    newTag: prod-latest
  - name: circleguard-promotion-service
    newTag: prod-latest
  - name: circleguard-notification-service
    newTag: prod-latest
  - name: circleguard-dashboard-service
    newTag: prod-latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: auth-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: promotion-service
