# Sealed Secrets — migración de k8s/base/01-secrets.yaml a formato cifrado.
#
# Valores encryptedData REALES, generados con kubeseal contra la clave pública
# del controlador (bitnami/sealed-secrets-controller:0.26.3) en este cluster.
#
# Regenerar (si se rota la clave del controlador):
#   kubeseal --fetch-cert --controller-name=sealed-secrets-controller \
#     --controller-namespace=kube-system > /tmp/pub-cert.pem
#   kubeseal --cert /tmp/pub-cert.pem --format yaml < k8s/base/01-secrets.yaml \
#     > k8s/security/01-sealed-secrets.yaml   # (con namespace: circleguard-dev)
#   kubectl apply -f k8s/security/01-sealed-secrets.yaml
#
# El controlador desencripta automáticamente el SealedSecret en un Secret Opaque.

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: circleguard-db-secret
  namespace: circleguard-dev
spec:
  encryptedData:
    neo4j-password: AgCjiucwOKK2NfZlWwvmHZSYRvMeHbxZKAImKTSQGVDnSZhNoYK0afmN5VmXsbzKenE7kMQF/OQ6OqS6n4cL5tdzZBlqxxyjEXOvKUmzJ1D9mKgNbYaixZN0jPTeP7xwkm9OKoCHukIftToCLjRn+ub8QYb4f5C+l2ACqN+oBgTHntrdKsjujQN+BZ19pn9jY4Km5uQd64D2QNgVP5HZh2jwk9oaFBXMjJbZfmISQG2IAZG6aX/YUxlHvS8GHpPLKkuP5w1/vN1vhhR5fb89OViEAn6HM5q1UnloM6/hKqsOaSMVihcDHzwZaeS1HJsf2oH2uHd7+hRn2njMtmPAzhTZrPpmaWq62BJbuj9kMk8YGTneL1Pkbiz/ZTqsS7EeWb+yZANID4jl5p2huHQuvzAcf0Qh9f+eNSkimbG/7ZUIXKb4SqH2+ThasT9ra73Fm2y47rs/S0DW9w/vQaIsOJFeeFU1W80v4ohMuuZ3oViThkIR1ZKd2PxUEo7VvVjheR9hyEZGM0hp40u1xsJIzoltzb0q15IfZubGTimLiYWHU+ow7dKWIjLH9FYVp1JK0Iy202/QU8frRsNq4vzLWoChAWInqKRdnpEZmEbkKxN0VmVXSFAOlgw4bUoPlQ02T4MrJLriKTTl7G4fdA1uukXyiUs0RfKj61lCad5/MKijcfMhb7awSNq258isl94dRSlKz34MjYfvRQ==
    postgres-password: AgB2ggm9toI6CM8xtFTxlxwYHVifC4B30lCX+iwBaXVI6iA/cGJZC6lIVz4YbE6FNmBOJ7N4usLYf3+KjZqlVyWYYPzcRBIRDhpsLxC6SA0VJnF3P7LfWV8CSx9AoCffjFqYrFuWnPHgEzfgRI6op+GJCUhs2hICV0CCskc24FMCKvI+2a5t7jgWtkbYg5qmMrkYf6+PXdp4oPV0/1lMf0tbBaESQR8E3Jr4vVKqP8RKahd6qvqqgkSAJADCJvIBq02gZTuZNSITzZW+UJEQ0MpgZONID9vOE4QQQGw6rEnrpGW42YV3RcmenkrXFgXIXB7MnISFHw/pSFc87QPLVo79+G8RyCErTISpmzwsD2IKGQt12HL+d+Ei3KO2oGjx+McUoHL3NkPFTZ1bYy2mVc5OofUhGTPYDf2ZLP5xH269vDfRm8B9Y4N6Y9e/4GT4YbhzNIg8q+XjHEo5UeN6qed+96SOnm4KAACp2vyUQfPD5NO1ZjCvEB9B3JFjN7/BOsHBQlMDNjVvvFmmEFe1/GeJogRu0iHFPmfh/UOeFnePAf6MaobYk33H2pSjM0BX2TOjdI7ZM8KaE7W5jCiDS9c6KpJxotoTuwpwEJb+QMhKxW7EKRPf8WsxEbLKvGGQZ3QTE3kEfIPORSpz00gPkb5h5LE82/5o+lBCMcG73TQu94RACMZiUvjmffwty5AFmATw/KEITcbuOQ==
    postgres-user: AgBQYQIgBMhzqUJWfTMqGSkkGeYy7mODC2x8/pq+/O2we4/1fwqKnDqC3OXXjoUvu1Y4znOhsojej8FxRFhHg9MbOjesIBeM4GZrLBJXNYsHu23Ny2TmqUj0i2ZMLioDoGJoPwi65OA2aff0NUHi2NiORRRbZk7L+iQMDfqm0YJ8xCX/8ZwAH94G3kP8Z0S3vrp9Yv7mQ46WeL+c/uT/q3NW/qJ7Mpgfp7hDcJV3VIjVE7JEKJg8N+Bby66yH+P2F2H3OC/MGuLAlR55uP4XN1+1U+K8iehfzf7TtA28oNo1fO5eskqeSpOMb0b1dJNkkmpThDr0AWYla7p/ZnFhpZ3U2Fhq5lpM2b15sZYfWjedHDIiTUehAIX26DLDmDoLjtzBm6U2VNzlBrrkQAx160ZMTA06JLiCqbsAfnSpTEiT48Z85XtV+TEpS+K/kqFIb3367tHF9zNxNGiHwidc7rbZx2+LW4D3TIw0/FpAXre7BzsI7ZCE0wsYypml7NU3pVeE6ATj6bKO4pGZMepaQCosVcf+N/Fe5P8bZX0EnHQa0jRXZPGnW1y9BrrHFo0kgeK+qHiukNtuABoo9SFLeSLLqqUx2SCRt9ezEGbhKWo9/3GGqr79aWk4Q5KnqwFon1lCMumORCu6kAt60rqC1a+Y8oFhia/+ti2fGZu275E+QUoOozAmtEKtmMNtZkKhITSjZhEOaQ==
  template:
    metadata:
      creationTimestamp: null
      name: circleguard-db-secret
      namespace: circleguard-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: circleguard-app-secret
  namespace: circleguard-dev
spec:
  encryptedData:
    jwt-secret: AgBc5wTGDK2mkvosSW58GybQgkugjO9BDXRkMyfq711t1JAUk5gnZk4ni4m4IjktbZmNnyk10jG5sUdEurcs/CZ4/NWgb1hL3i0j+pJMS7XDYEggDe85xEidRXGSUXUCBzrRcDTeEPQXHJvEIJLc+PYuJo2AqQS7ClubMMEKUnsaTP8SMxzLKR4lA5iHUikFSgdQfvVG9dl++WlhnzEJH7FwqKhr7a0Gm7by/R2ztGi5HCMN1a2jlhP1qsP/HvfTqyXqexuMc/GG8aRMbOsUF7fJREII7ooHMpCO49WlyuwItDz4GCodBrIb5yL91b5IZiURp6JpEbBIRLGGTNS8uYfCd/Vf3CNPeJD5GrUJ2tSWW6rtvQMLniQMluZMf5qldBgYlhhzzrUA1CFayca8CGcY6rE3IQ4bfoB51Nwu5gvZ24bybd1YZtEfCIDGFwF8+TXpHXxuJJH4Lb5oSPGEjFLQN8+z+A43dUvyvEFiUuZLDCsjStIpq/ukCAThMrtdiBDYnpBFE8rEaHKyZFasiOO8kl6vD6sLkV37IJFPAHxr7KmGvxXqmPxI+iFX35RUUipf2Ci0zAmdrWuR1UXBTQKr3ysEtrEE9IhZjmqNroZbgybLnK9nVGntq39orf3I79HiKniMkCH+POY6f4KP8Og+efUPujiDM51tOKdXHiJUgTAFbA+WWnGkXuKwpupp2sE77ycl4xh18jzlDs0BK/R0Dm1UJChNeoaK41yka13AUpYD0caE90dQcAz1ZAWi/Ukf6lVYCSjOnJAiDSpWBvQN6g==
    vault-hash-salt: AgBzDTMzjeaf/ixAOi7U/jFzraNTbjd4isU/nHsYoh0yIKYhrN0lZc4MFuX3h9gVttVQqUr3sjGOTLIjk3DjOY8VWTWhockM+O9r5frDGtw1BSv3znwjy6zxvE7Z79NX3GnTVcBBtHuENi17FU/9wWt6KjJK/hQ2Oq3hvhx7SM3Pnb3fDkmnZbKbIMrZuCGNNy6RipEYP2yvSboOgkTyebB5FGMNrnnPsc4glAQimZGfy1ky8CKPUU0RmxsfvjEXWGA1x+noftq1tmwxfvBaA2r9D1Q7NtOSsYag/StODuMCMr8NvPhoZFeC19c62OHghGc2o6YjIcOU2WvaZW9ZWWG0xkfMGN2b/MJY/PF2vtK6cAKyjVGiFfBGWOWD4n1EgEZK0Db4Kab/BxWlj5LsGCYO03+j55MhQ/1nNAQZEhVVnwis0Mw24FA4Ol11d/N5kqm7DlEyAqpCewHFgarWQxaagNemEcThwgujj6nkKu8PI9Ea1Pqnf2SqEojRs5hz21R11e777GLRvdctZO1PFHOgQ1+tWWBikiR81o4PQm5Ry/QyYaclUnYWvXA1VEGfKMGKCovR5kzW9I/c5xJkmKxfKxvfM13chGiY9L85vRL/gFsUOabtZEdPCZqMuuUIKdyW3e8qzhznjpxnWcBhVAvNOV1sJFe+PiB/rU8IflIq8MjXrOzjlLvFRS24vRkC0/jXMtaNJPh4kKKkO8ASHpCn
  template:
    metadata:
      creationTimestamp: null
      name: circleguard-app-secret
      namespace: circleguard-dev
    type: Opaque
